name: preflight
services:
  postgres:
    image: postgres:16-alpine
    container_name: pf-db
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pf-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - pf-net
  backend:
    depends_on:
      - postgres
    image: nnnpooh/preflight-backend:latest
    container_name: pf-backend
    ports:
      - ${PORT}:3000
    networks:
      - pf-net
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
  frontend:
    depends_on:
      - backend
    image: nnnpooh/preflight-frontend:latest
    container_name: pf-frontend
    ports:
      - ${NGINX_PORT}:5173
    networks:
      - pf-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}
volumes:
  pf-data:
networks:
  pf-net: